### ISSUE TITLE
pandoc-include-code returns 'Incompatible API versions' in Pandoc 2.8.0.1

### ISSUE THREAD

**Issue by aubertc** [jgm/pandoc#5943]
I am facing the same error message as in this [other issue](https://github.com/jgm/pandoc/issues/5935), but cannot solve it.

```
$ pandoc -v
pandoc 2.8.0.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
```
For a dummy `min.md`, I have:

```
$ pandoc --filter pandoc-include-code min.md 
pandoc-include-code: Error in $: Incompatible API versions: encoded with [1,20] but attempted to decode with [1,17,5,4].
CallStack (from HasCallStack):
  error, called at ./Text/Pandoc/JSON.hs:111:48 in pandoc-types-1.17.5.4-22S5sdSWY1o40P5WSw9yTF:Text.Pandoc.JSON
Error running filter pandoc-include-code:
Filter returned error status 1
```
(even if `min.md` does *not* contains any include command).

Facing a similar issue with , @jgm  recommended:

> You'll have to use a version of pandoc-citeproc that was compiled against pandoc-types 1.20 (like pandoc 2.8). The binary packages of pandoc sholud contain a compatible version. if you installed pandoc by source, you'll need to reinstall pandoc-types too.

I have re-installed pandoc-include-code-1.4.0.0 from the source but it did not make any change.

**Comment by jgm** [comment]
You'll need to make sure that when you recompile pandoc-include-code, it is using pandoc-types-1.20 and not earlier versions.  The package has a constraint to pandoc-types < 1.19; so unless you've done something special it will not have compiled against pandoc-types 1.20.  You can try telling cabal or stack to "allow newer" (see elsewhere for the syntax) -- this may or may not work depending on what the filter does -- and you can ask the maintainer to fix it so it compiles with pandoc-types 1.20.

**Comment by aubertc** [comment]
Ok, thanks a lot for the recommendations, I'll investigate and reports my findings, if any.

**Comment by aubertc** [comment]
Thanks again for your comment.
Unfortunately, the package does not compile with newer versions of pandoc-types (cf. below), so some editing in the source code will be needed.

I'll see if the developer can do something, or try to write a PR myself.

```
cabal --allow-newer=pandoc-types install

Resolving dependencies...
Configuring pandoc-include-code-1.4.0.0...
Building pandoc-include-code-1.4.0.0...
Failed to install pandoc-include-code-1.4.0.0
Build log ( /home/caubert/.cabal/logs/ghc-8.4.4/pandoc-include-code-1.4.0.0-EJrJG0p2lz0JtH2D1u7k5W.log ):
cabal: Entering directory '.'
Configuring pandoc-include-code-1.4.0.0...
Preprocessing library for pandoc-include-code-1.4.0.0..
Building library for pandoc-include-code-1.4.0.0..
[1 of 2] Compiling Text.Pandoc.Filter.Range ( src/Text/Pandoc/Filter/Range.hs, dist/build/Text/Pandoc/Filter/Range.o )
[2 of 2] Compiling Text.Pandoc.Filter.IncludeCode ( src/Text/Pandoc/Filter/IncludeCode.hs, dist/build/Text/Pandoc/Filter/IncludeCode.o )

src/Text/Pandoc/Filter/IncludeCode.hs:197:24: error:
    • Couldn't match type ‘Text’ with ‘[Char]’
      Expected type: HashMap String String
        Actual type: HashMap Text Text
    • In the first argument of ‘parseInclusion’, namely
        ‘(HM.fromList attrs)’
      In the expression: parseInclusion (HM.fromList attrs)
      In the expression:
        case parseInclusion (HM.fromList attrs) of
          Right (Just spec)
            -> runInclusion' spec allSteps
                 >>=
                   \case
                     Left err -> return (Left err)
                     Right (contents, state)
                       -> return
                            (Right
                               (CodeBlock
                                  (id', classes, modifyAttributes state classes attrs)
                                  (Text.unpack contents)))
          Right Nothing -> return (Right cb)
          Left err -> return (Left err)
    |
197 |   case parseInclusion (HM.fromList attrs) of
    |                        ^^^^^^^^^^^^^^^^^

src/Text/Pandoc/Filter/IncludeCode.hs:205:34: error:
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected type: [(Text, Text)]
        Actual type: [(String, String)]
    • In the expression: modifyAttributes state classes attrs
      In the first argument of ‘CodeBlock’, namely
        ‘(id', classes, modifyAttributes state classes attrs)’
      In the first argument of ‘Right’, namely
        ‘(CodeBlock
            (id', classes, modifyAttributes state classes attrs)
            (Text.unpack contents))’
    |
205 |                   (id', classes, modifyAttributes state classes attrs)
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Text/Pandoc/Filter/IncludeCode.hs:205:57: error:
    • Couldn't match type ‘Text’ with ‘[Char]’
      Expected type: [String]
        Actual type: [Text]
    • In the second argument of ‘modifyAttributes’, namely ‘classes’
      In the expression: modifyAttributes state classes attrs
      In the first argument of ‘CodeBlock’, namely
        ‘(id', classes, modifyAttributes state classes attrs)’
    |
205 |                   (id', classes, modifyAttributes state classes attrs)
    |                                                         ^^^^^^^

src/Text/Pandoc/Filter/IncludeCode.hs:205:65: error:
    • Couldn't match type ‘Text’ with ‘[Char]’
      Expected type: [(String, String)]
        Actual type: [(Text, Text)]
    • In the third argument of ‘modifyAttributes’, namely ‘attrs’
      In the expression: modifyAttributes state classes attrs
      In the first argument of ‘CodeBlock’, namely
        ‘(id', classes, modifyAttributes state classes attrs)’
    |
205 |                   (id', classes, modifyAttributes state classes attrs)
    |                                                                 ^^^^^

src/Text/Pandoc/Filter/IncludeCode.hs:206:20: error:
    • Couldn't match type ‘[Char]’ with ‘Text’
      Expected type: Text
        Actual type: String
    • In the second argument of ‘CodeBlock’, namely
        ‘(Text.unpack contents)’
      In the first argument of ‘Right’, namely
        ‘(CodeBlock
            (id', classes, modifyAttributes state classes attrs)
            (Text.unpack contents))’
      In the first argument of ‘return’, namely
        ‘(Right
            (CodeBlock
               (id', classes, modifyAttributes state classes attrs)
               (Text.unpack contents)))’
    |
206 |                   (Text.unpack contents)))
    |                    ^^^^^^^^^^^^^^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
pandoc-include-code-1.4.0.0-EJrJG0p2lz0JtH2D1u7k5W failed during the building
phase. The exception was:
ExitFailure 1


```
