### ISSUE TITLE
Exception when trying to run compile-time code: Data/Aeson/TH.hs:(1038,7)-(1046,14): Irrefutable pattern failed for pattern x : xs

### ISSUE THREAD

**Issue by wilx** [jgm/pandoc#4192]
I have just tried to compile Pandoc using Cabal but got this error:

```
[ 35 of 119] Compiling Text.Pandoc.Options ( src/Text/Pandoc/Options.hs, dist/build/Text/Pandoc/Options.o )

src/Text/Pandoc/Options.hs:1:1: error:
    Exception when trying to run compile-time code:
      Data/Aeson/TH.hs:(1038,7)-(1046,14): Irrefutable pattern failed for pattern x : xs

    Code: deriveJSON defaultOptions ''ReaderOptions
cabal: Leaving directory '/tmp/cabal-tmp-9109/pandoc-2.0.5'
cabal: Error: some packages failed to install:
pandoc-2.0.5-5Gz5rYddEd565ASAVhajXl failed during the building phase. The
exception was:
ExitFailure 1
pandoc-citeproc-0.12.1.1-B9S7AxZsjCt3dif3FBgMcR depends on
pandoc-citeproc-0.12.1.1 which failed to install.
```

**Comment by wilx** [comment]
This was with The Glorious Glasgow Haskell Compilation System, version 8.0.2 on Linux.

**Comment by jgm** [comment]
Do your logs show which version of aeson was being used?

We compile all the time with 8.0.2 + cabal on Travis, but perhaps this is a change in aeson?
In any case, it looks more likely to be a bug in aeson than in pandoc.

**Comment by jgm** [comment]
Latest build on travis with cabal + 8.0.2:
https://travis-ci.org/jgm/pandoc/jobs/320636399
It's using aeson 1.2.2.0.  Not sure why cabal didn't select aeson 1.2.3.0 the latest version.  But the cabal build with ghc 8.2.2 and the stack build both use aeson 1.2.3.0.

**Comment by wilx** [comment]
I have blown up `~/.cabal` and `~/.ghc` and then retried the build. It worked this way. It used aeson-1.2.3.0.
