### PR TITLE
Fixed linker error on macOS/OS X 10.9+

### LINKED ISSUE #3291: Linker error on macOS/OS X 10.9+
Hey,

I ran into a problem trying to build the project with `stack build` or `stack install` on macOS/OS X version >= 10.9. It spits out this linker error:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1) 
```

Cheers,
Tomas

### PR DESCRIPTION
**Pull request by maseek**
I ran into a problem trying to build the project with stack build or
stack install on macOS/OS X version >= 10.9. It spits out this linker
error:
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

I've added `-stdlib=libstdc++` cpp flag to link against libstdc++
instead of libc++ which is default from OS X version 10.9 up.

Fixes #3291

### CODE REVIEW

**Comment by jgm** [comment]
I'm confused, because we regularly build pandoc on OSX >= 10.9.
Here's a successful travis build on 10.11:
https://travis-ci.org/jgm/pandoc/jobs/182257383
Nor have I heard any other talk in the Haskell community about the need for this option on OSX.
So I'm reluctant to merge this until I understand the situation better.
