### ISSUE TITLE
Build failure for pandoc 1.15.0.4 on OpenBSD

### ISSUE THREAD

**Issue by klpn** [jgm/pandoc#2271]
When I try to install pandoc 1.15.0.4 on OpenBSD (latest snapshot for amd64) with ghc 7.8.4 (latest version available for this system), the build fails with a [long list with undefined references to regex-pcre-builtin](https://gist.github.com/klpn/3a6856a0efdcbcea0d17). I have tried to build with fpcre-light: `cabal install --reinstall --force highlighting-kate pandoc -fpcre-light`.  However, this also fails due to this error: 
`/home/karl/.cabal/lib/x86_64-openbsd-ghc-7.8.4/texmath-0.8.1/libHStexmath-0.8.1.a(ToASCII.o):(.text+0x40): undefined reference to 'keylookup'`

I have experienced similar errors with pandoc 1.13.2 och 1.14.0.4 on OpenBSD 5.6 and 5.7.

**Comment by jgm** [comment]
These all have to do with Haskell packages that include `cbits` (C code that is compiled and linked automatically in the build process).  In the case of `texmath`, `keylookup` is a big lookup table that we coded in C to speed up compilation.  In pcre-regex-builtin, the pcre library is all in `cbits` (hence the "built-in" -- the idea is to allow pandoc to be installed even if you don't have the pcre library installed independently).

I have no idea why this doesn't work on OpenBSD, but it's not a pandoc-specific issue.  I suggest you ask on the [haskell cafe](https://mail.haskell.org/mailman/listinfo/haskell-cafe) mailing list or the [haskell reddit](https://www.reddit.com/r/haskell).  Focus your question on pcre-regex-builtin, and just post output from `cabal install pcre-regex-builtin`.  Hopefully someone there will be able to help.

**Comment by aaren** [comment]
@klpn did you find a solution? I'm also having this problem on CentOS 5.

**Comment by klpn** [comment]
It builds if I use the Haskell platform packaged with OpenBSD 5.6 (which includes ghc 7.6.3, rather than ghc 7.8.4), and perhaps it has to do with the ghc version. The tested versions listed in `pandoc.cabal` are 7.4.2, 7.6.3 and 7.8.2. I have also succeeded in building with ghc 7.10.1 on Arch.

**Comment by aaren** [comment]
Changing to ghc 7.6.3 fixed my issue (the undefined reference to keylookup in texmath). I was trying to build with ghc 7.8.2 before. 

Build process was the same for both ghc versions:

```
cabal install pcre-light   # using locally built pcre 8.37
cabal install --only-dependencies pandoc
cabal install --force --reinstall highlighting-kate -fpcre-light
cabal install pandoc -fpcre-light
```

but with ghc 7.8.2 I get the texmath error.

I'm not using haskell platform (this is painful on my system), just ghc and cabal.

Thanks for the tip!

**Comment by mkilian** [comment]
For those running OpenBSD current: I just committed kind of a workaround to our ghc port. Just wait a few days until new snapshot packages hit the mirrors. If  the pkg name of ghc is ghc-7.10.2p0, you should be fine.

aaren: you said that changing from 7.8.2 to 7.8.3 fixed the issue in texmath. Did you build it yourself from ports, did you following OpenBSD-current and just got the update via packages, or something else?

I'm asking because the problem is related to the fact the Cabal runs strip --strip-unneeded on the generated libraries, and for yet unknown reasons, this appears to fail sometimes (on OpenBSD). I don't understand how an update from 7.8.2. to 7.8.3 could have magically fixed that problem ;-)

**Comment by klpn** [comment]
I made it work by downgrading from 7.8.4 to 7.**6**.3 (and it seems that aaren also downgraded from 7.8.2 to 7.6.3).

**Comment by aaren** [comment]
@mkilian i'm actually on centos 5, not openbsd.

**Comment by jirib** [comment]
I hit similar issue on OpenBSD:
1. undefined references to pcre
2. undefined references to llua
3. undefined reference to `keylookup'

1 + 2 I solved with:

```
cabal build -v3 -j --ghc-options="-optl=-lpcre -llua5.1"
```

I'll wait for ghc-7.10.2p0 as stated by mkilian. Will ghc-7.10.2p0 solve 1. and 2. as well without adding -lpcre and -llua5.1 to linking phase?

**Comment by jirib** [comment]
I built with ghc-7.10.2p0 and everything was neat without any human intervention (thus no --ghc-options="-optl=-lpcre -llua5.1").
