### ISSUE TITLE
pandoc doesn't build with cabal 3.8.1.0, ghc 9.4.2

### ISSUE THREAD

**Issue by essandess** [jgm/pandoc#8276]
`cabal build exe:pandoc --allow-newer=base` throws these compile-time errors:
<details>

```
:info:build Data/ByteString/Builder/Prim/Internal/UncheckedShifts.hs:74:36: error:
:info:build     • Couldn't match expected type ‘Word16#’ with actual type ‘Word#’
:info:build     • In the first argument of ‘W16#’, namely
:info:build         ‘(w `uncheckedShiftRL#` i)’
:info:build       In the expression: W16# (w `uncheckedShiftRL#` i)
:info:build       In an equation for ‘shiftr_w16’:
:info:build           shiftr_w16 (W16# w) (I# i) = W16# (w `uncheckedShiftRL#` i)
:info:build    |
:info:build 74 | shiftr_w16 (W16# w) (I# i) = W16# (w `uncheckedShiftRL#`   i)
:info:build    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
:info:build Data/ByteString/Builder/Prim/Internal/UncheckedShifts.hs:75:36: error:
:info:build     • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
:info:build     • In the first argument of ‘W32#’, namely
:info:build         ‘(w `uncheckedShiftRL#` i)’
:info:build       In the expression: W32# (w `uncheckedShiftRL#` i)
:info:build       In an equation for ‘shiftr_w32’:
:info:build           shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#` i)
:info:build    |
:info:build 75 | shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#`   i)
:info:build    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
:info:build Data/ByteString/Builder/Prim/Internal/UncheckedShifts.hs:80:36: error:
:info:build     • Couldn't match expected type ‘Word64#’ with actual type ‘Word#’
:info:build     • In the first argument of ‘W64#’, namely
:info:build         ‘(w `uncheckedShiftRL#` i)’
:info:build       In the expression: W64# (w `uncheckedShiftRL#` i)
:info:build       In an equation for ‘shiftr_w64’:
:info:build           shiftr_w64 (W64# w) (I# i) = W64# (w `uncheckedShiftRL#` i)
:info:build    |
:info:build 80 | shiftr_w64 (W64# w) (I# i) = W64# (w `uncheckedShiftRL#` i)
```

**Comment by jgm** [comment]
I get:
```
Data/Memory/Internal/CompatPrim64.hs:22:7: error:
    Ambiguous occurrence ‘eqInt64#’
    It could refer to
       either ‘GHC.Prim.eqInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.eqInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:85:1
   |
22 |     , eqInt64#
   |       ^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:23:7: error:
    Ambiguous occurrence ‘neInt64#’
    It could refer to
       either ‘GHC.Prim.neInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.neInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:88:1
   |
23 |     , neInt64#
   |       ^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:24:7: error:
    Ambiguous occurrence ‘ltInt64#’
    It could refer to
       either ‘GHC.Prim.ltInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.ltInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:91:1
   |
24 |     , ltInt64#
   |       ^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:25:7: error:
    Ambiguous occurrence ‘leInt64#’
    It could refer to
       either ‘GHC.Prim.leInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.leInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:94:1
   |
25 |     , leInt64#
   |       ^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:26:7: error:
    Ambiguous occurrence ‘gtInt64#’
    It could refer to
       either ‘GHC.Prim.gtInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.gtInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:97:1
   |
26 |     , gtInt64#
   |       ^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:27:7: error:
    Ambiguous occurrence ‘geInt64#’
    It could refer to
       either ‘GHC.Prim.geInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.geInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:100:1
   |
27 |     , geInt64#
   |       ^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:28:7: error:
    Ambiguous occurrence ‘quotInt64#’
    It could refer to
       either ‘GHC.Prim.quotInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.quotInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:103:1
   |
28 |     , quotInt64#
   |       ^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:29:7: error:
    Ambiguous occurrence ‘remInt64#’
    It could refer to
       either ‘GHC.Prim.remInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.remInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:106:1
   |
29 |     , remInt64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:30:7: error:
    Ambiguous occurrence ‘eqWord64#’
    It could refer to
       either ‘GHC.Prim.eqWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.eqWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:67:1
   |
30 |     , eqWord64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:31:7: error:
    Ambiguous occurrence ‘neWord64#’
    It could refer to
       either ‘GHC.Prim.neWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.neWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:70:1
   |
31 |     , neWord64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:32:7: error:
    Ambiguous occurrence ‘ltWord64#’
    It could refer to
       either ‘GHC.Prim.ltWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.ltWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:73:1
   |
32 |     , ltWord64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:33:7: error:
    Ambiguous occurrence ‘leWord64#’
    It could refer to
       either ‘GHC.Prim.leWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.leWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:76:1
   |
33 |     , leWord64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:34:7: error:
    Ambiguous occurrence ‘gtWord64#’
    It could refer to
       either ‘GHC.Prim.gtWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.gtWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:79:1
   |
34 |     , gtWord64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:35:7: error:
    Ambiguous occurrence ‘geWord64#’
    It could refer to
       either ‘GHC.Prim.geWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.geWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:82:1
   |
35 |     , geWord64#
   |       ^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:36:7: error:
    Ambiguous occurrence ‘and64#’
    It could refer to
       either ‘GHC.Prim.and64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.and64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:109:1
   |
36 |     , and64#
   |       ^^^^^^

Data/Memory/Internal/CompatPrim64.hs:37:7: error:
    Ambiguous occurrence ‘or64#’
    It could refer to
       either ‘GHC.Prim.or64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.or64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:112:1
   |
37 |     , or64#
   |       ^^^^^

Data/Memory/Internal/CompatPrim64.hs:38:7: error:
    Ambiguous occurrence ‘xor64#’
    It could refer to
       either ‘GHC.Prim.xor64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.xor64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:115:1
   |
38 |     , xor64#
   |       ^^^^^^

Data/Memory/Internal/CompatPrim64.hs:39:7: error:
    Ambiguous occurrence ‘not64#’
    It could refer to
       either ‘GHC.Prim.not64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.not64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:118:1
   |
39 |     , not64#
   |       ^^^^^^

Data/Memory/Internal/CompatPrim64.hs:40:7: error:
    Ambiguous occurrence ‘timesWord64#’
    It could refer to
       either ‘GHC.Prim.timesWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.timesWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:145:1
   |
40 |     , timesWord64#
   |       ^^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:41:7: error:
    Ambiguous occurrence ‘uncheckedShiftL64#’
    It could refer to
       either ‘GHC.Prim.uncheckedShiftL64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.uncheckedShiftL64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:121:1
   |
41 |     , uncheckedShiftL64#
   |       ^^^^^^^^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:42:7: error:
    Ambiguous occurrence ‘uncheckedShiftRL64#’
    It could refer to
       either ‘GHC.Prim.uncheckedShiftRL64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.uncheckedShiftRL64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:124:1
   |
42 |     , uncheckedShiftRL64#
   |       ^^^^^^^^^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:44:7: error:
    Ambiguous occurrence ‘int64ToWord64#’
    It could refer to
       either ‘GHC.Prim.int64ToWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.int64ToWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:127:1
   |
44 |     , int64ToWord64#
   |       ^^^^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:45:7: error:
    Ambiguous occurrence ‘word64ToInt64#’
    It could refer to
       either ‘GHC.Prim.word64ToInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.word64ToInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:130:1
   |
45 |     , word64ToInt64#
   |       ^^^^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:46:7: error:
    Ambiguous occurrence ‘intToInt64#’
    It could refer to
       either ‘GHC.Prim.intToInt64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.intToInt64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:133:1
   |
46 |     , intToInt64#
   |       ^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:47:7: error:
    Ambiguous occurrence ‘int64ToInt#’
    It could refer to
       either ‘GHC.Prim.int64ToInt#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.int64ToInt#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:136:1
   |
47 |     , int64ToInt#
   |       ^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:48:7: error:
    Ambiguous occurrence ‘wordToWord64#’
    It could refer to
       either ‘GHC.Prim.wordToWord64#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.wordToWord64#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:139:1
   |
48 |     , wordToWord64#
   |       ^^^^^^^^^^^^^

Data/Memory/Internal/CompatPrim64.hs:49:7: error:
    Ambiguous occurrence ‘word64ToWord#’
    It could refer to
       either ‘GHC.Prim.word64ToWord#’,
              imported from ‘GHC.Prim’ at Data/Memory/Internal/CompatPrim64.hs:55:1-40
           or ‘Data.Memory.Internal.CompatPrim64.word64ToWord#’,
              defined at Data/Memory/Internal/CompatPrim64.hs:142:1
   |
49 |     , word64ToWord#
   |       ^^^^^^^^^^^^^

Error: cabal: Failed to build memory-0.17.0 (which is required by
test:test-pandoc from pandoc-2.19.2). See the build log above for details.
```

This is a problem in one of pandoc's dependencies, not in pandoc itself.
The bug has already been reported at https://github.com/vincenthz/hs-memory/issues/94
When it is fixed there, we can proceed further, but we'll have to wait until all of pandoc's dependencies compile before we can build pandoc.
