### ISSUE TITLE
pthread link errors on linux with GHC 8.2

### ISSUE THREAD

**Issue by simonmichael** [jgm/pandoc#4130]
On Ubuntu 16.04.1 LTS, stack install pandoc-2.0.4 is failing to link pthread functions:
```
...
[116 of 116] Compiling Text.Pandoc.App  ( src/Text/Pandoc/App.hs, .stack-work/dist/i386-linux/Cabal-2.0.1.0/build/Text/Pandoc/App.o )                                                                                                                      
    Preprocessing executable 'pandoc' for pandoc-2.0.4..                                                                                                                                                                                                       
    Building executable 'pandoc' for pandoc-2.0.4..                                                                                                                                                                                                            
    [1 of 2] Compiling Main             ( pandoc.hs, .stack-work/dist/i386-linux/Cabal-2.0.1.0/build/pandoc/pandoc-tmp/Main.o )                                                                                                                                
    [2 of 2] Compiling Paths_pandoc     ( .stack-work/dist/i386-linux/Cabal-2.0.1.0/build/pandoc/autogen/Paths_pandoc.hs, .stack-work/dist/i386-linux/Cabal-2.0.1.0/build/pandoc/pandoc-tmp/Paths_pandoc.o )                                                   
    Linking .stack-work/dist/i386-linux/Cabal-2.0.1.0/build/pandoc/pandoc ...                                                                                                                                                                                  
                                                                                                                                                                                                                                                               
    /tmp/stack14939/pandoc-2.0.4/rts/posix/OSThreads.c:137:0: error:                                                                                                                                                                                           
         error: undefined reference to 'pthread_create'                                                                                                                                                                                                        
                                                                                                                                                                                                                                                               
    /tmp/stack14939/pandoc-2.0.4/rts/posix/OSThreads.c:139:0: error:                                                                                                                                                                                           
         error: undefined reference to 'pthread_detach'                   
...
```

Is there an ubuntu package I'm missing ? I didn't see this error when building 1.x.

**Comment by jgm** [comment]
This is with normal 'stack install'?  Any special options?
What ghc and stack versions?

**Comment by mb21** [comment]
If this is [this ghc bug](https://ghc.haskell.org/trac/ghc/ticket/12816) it should be fixed in GHC 8.1

**Comment by simonmichael** [comment]
This is a normal stack install, stack 1.6.1, nightly-2017-12-05 resolver, ghc 8.2.2.

**Comment by jgm** [comment]
This is odd, because we regularly do builds with cabal and
ghc 8.2.2 on travis-ci, which uses Ubuntu.

I noticed that we have a stack build with ghc 8.2.2 and
nightly on ci, and it fails for the reasons you report:
https://travis-ci.org/jgm/pandoc/jobs/312704463

I never looked into why, but we should figure this out.
Cabal seems to work fine...

+++ Simon Michael [Dec 07 17 22:44 ]:

**Comment by simonmichael** [comment]
More testing on this system:

`stack install --resolver lts-9.17` in the pandoc source tree at 2.0.4 tag links successfully. (GHC 8.0.2)

`cabal install pandoc-2.0.4` links successfully. This used the system GHC. (GHC 7.10.3)

`cabal install pandoc-2.0.4 -w /home/simon/.stack/programs/i386-linux/ghc-8.2.2/bin/ghc` fails with the same error. (GHC 8.2.2)
```
$ cabal install pandoc-2.0.4 -j -w /home/simon/.stack/programs/i386-linux/ghc-8.2.2/bin/ghc
...
Linking dist/build/pandoc/pandoc ...                                                                                                                                                 
                                                                                                                                                                                     
rts/posix/OSThreads.c:137:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_create'                                                                                                                                  
                                                                                                                                                                                     
rts/posix/OSThreads.c:139:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_detach'                                                                                                                                  
                                                                                                                                                                                     
rts/posix/OSThreads.c:141:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_setname_np'                                                                                                                              
                                                                                                                                                                                     
rts/posix/OSThreads.c:184:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_key_create'                                                                                                                              
                                                                                                                                                                                     
rts/posix/OSThreads.c:192:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_getspecific'                                                                                                                             
                                                                                                                                                                                     
rts/posix/OSThreads.c:203:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_setspecific'                                                                                                                             
                                                                                                                                                                                     
rts/posix/OSThreads.c:212:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_key_delete'                                                                                                                              
                                                                                                                                                                                     
rts/posix/OSThreads.c:371:0: error:                                                                                                                                                  
     error: undefined reference to 'pthread_kill'                                                                                                                                    
                                                                                                                                                                                     
includes/rts/OSThreads.h:59:0: error:                                                                                                                                                
     error: undefined reference to 'pthread_mutex_trylock'                                                                                                                           
collect2: error: ld returned 1 exit status                                                                                                                                           
`gcc' failed in phase `Linker'. (Exit code: 1)                                                                                                                                       
cabal: Leaving directory '/tmp/cabal-tmp-14784/pandoc-2.0.4'                                                                                                                         
cabal: Error: some packages failed to install:                                                                                                                                       
pandoc-2.0.4-3Gl6Xt4LcAi3gpzxmZMtTy failed during the building phase. The                                                                                                            
exception was:                                                                                                                                                                       
ExitFailure 1                                                                       
```

Following @mb21's lead: binutils on this system provides both ld and ld.gold. GHC 8.2.1 release notes say "GHC will now use ld.gold or ld.lld instead of the system’s default ld, if available. Linker availability will be evaluated at configure time. The user can manually override which linker to use by passing the LD variable to configure. You can revert to the old behavior of using the system’s default ld by passing the --disable-ld-override flag to configure." 

I tried replacing /usr/bin/{gold,ld.gold} with symlinks to ld. The format of the link error changed, but otherwise the error seemed the same.

**Comment by jgm** [comment]
I tried adding `-threaded` to the executable stanza of cabal.  Unfortunately, the travis build fails for stack + ghc 8.2.2 (looks like an out-of-memory issue compiling a dependent library).  But why don't you try with the latest pull from master.

**Comment by simonmichael** [comment]
@jgm: that fixed it with GHC 8.2.2 here.

**Comment by jgm** [comment]
Excellent, I'll close this then.

**Comment by simonmichael** [comment]
Thanks for the support! 

The cabal+ghc8.2 CI test probably should have failed like stack, it might need a tweak specifying GHC version.

**Comment by jgm** [comment]
+++ Simon Michael [Dec 08 17 21:16 ]:
>   Thanks for the support!
>
>   The cabal+ghc8.2 CI test probably should have failed like stack, it
>   might need a tweak specifying GHC version.

You can see from the log that it's using ghc 8.2.2.
So I don't know why this worked for me and failed for you...

**Comment by hanjoosten** [comment]
@jgm what exactly did you do to fix this? I am still struggling with the build of Ampersand, using pandoc 2.0.6 with ghc 8.2.2. It builds fine with cabal, but [the stack build fails](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/328723392), even as I enabled -threaded flag.

**Comment by jgm** [comment]
@hansjoosten it looks like it's pandoc-crossref that is failing in your build. Perhaps it needs the threaded flag in its cabal file?  If this works, you might alert the author.

**Comment by hanjoosten** [comment]
Thanks. I guess you are right. The -threaded option was only in the executable, not with the library. I asked @lierdakil to kindly add it.

**Comment by lierdakil** [comment]
```
Warning: 'ghc-options: -threaded' has no effect for libraries. It should only
be used for executables.
```
Did that change with GHC 8.2?

**Comment by jgm** [comment]
+++ Nikolay Yakimov [Jan 15 18 22:01 ]:
>Warning: 'ghc-options: -threaded' has no effect for libraries. It should only
>be used for executables.
>
>   Did that change with GHC 8.2?

I'm not aware of any such change.  In pandoc we only use
-threaded on the executable.
