### ISSUE TITLE
Error on install: src/Text/Pandoc/Shared.hs:808:55: Not in scope: `toChunks'

### ISSUE THREAD

**Issue by FloGa** [jgm/pandoc#1590]
I did a clean `cabal install` inside the working directory without any other options and it exits with an error stating that `toChunks` is not in scope in File Shared.hs.

Since I've never worked with Haskell before I can only give you my assumptions, but I guess it has something to do with the conditional import of `toChunks` and the non-conditional call in `fetchItem'`. If `HTTP_CLIENT` is not defined, then obviously there is the possibility of calling `toChunks` without ever importing it.

Furthermore, `git bisect` says that the first commit to contain this "bug" is 28321a18bfcf87e5a874ad86c0c7ec82ed3848e4 (2014-07-30: "Shared:  Added fetchItem', which searches a media bag too.").

(Tested with latest master commit 44559055506461d2c675f978182aa20ee689433e.)
