### ISSUE TITLE
Setup.hs broken by Cabal 2.x

### ISSUE THREAD

**Issue by peti** [jgm/pandoc#3876]
I cannot compile pandoc-1.19.2.1's `Setup.hs` file with GHC 8.2.1 because of the following issue:

~~~
Setup.hs:42:3: error:
    • Couldn't match expected type ‘ComponentLocalBuildInfo
                                    -> PreProcessor’
                  with actual type ‘PreProcessor’
    • In the expression:
        PreProcessor
          {platformIndependent = True,
           runPreProcessor = mkSimplePreProcessor
                               $ \ infile outfile verbosity
                                   -> do let ...
                                         ....}
      In the expression:
        \ _ lbi
          -> PreProcessor
               {platformIndependent = True,
                runPreProcessor = mkSimplePreProcessor
                                    $ \ infile outfile verbosity -> ...}
      In the expression:
        ("hsb", 
         \ _ lbi
           -> PreProcessor
                {platformIndependent = True,
                 runPreProcessor = mkSimplePreProcessor
                                     $ \ infile outfile verbosity -> ...})
   |
42 |   PreProcessor {
   |   ^^^^^^^^^^^^^^...

Setup.hs:45:39: error:
    Data constructor not in scope: FlagName :: [Char] -> FlagName
   |
45 |       do let embedData = case lookup (FlagName "embed_data_files")
   |                                       ^^^^^^^^
~~~

**Comment by mb21** [comment]
have you tried with current master?

**Comment by jgm** [comment]
We're focused on 2.0, which will build with Cabal 2.0.

As for backporting a build fix to 1.19.x, I'm not sure how to do it.  Is there a way to make sections in the Setup.hs file conditional on the Cabal version used?  Otherwise I don't know how to deal with the API change.  Or maybe we just add `< 2.0` to Cabal-Version, if that can be done?

**Comment by peti** [comment]
> Or maybe we just add `< 2.0` to Cabal-Version, if that can be done?

I believe that restriction belongs into the setup-dependencies stanza.

**Comment by jgm** [comment]
+++ Peter Simons [Sep 02 17 11:37 ]:
>     Or maybe we just add < 2.0 to Cabal-Version, if that can be done?
>
>   I believe that restriction belongs into the setup-dependencies stanza.

The problem is that if you use that stanza, a very recent
version of Cabal is required.  That is why I've resisted
adding it; I'd like pandoc to be buildable with ghc 8.2.1+
with the build tools that come with the compiler.

**Comment by ilovezfs** [comment]
@jgm the way to do this is described here: https://github.com/idris-lang/Idris-dev/issues/3956#issuecomment-319798788

**Comment by ilovezfs** [comment]
@jgm and the fix itself was in https://github.com/idris-lang/Idris-dev/pull/3968.

**Comment by peti** [comment]
https://github.com/jgm/pandoc/pull/3899 resolves the issue for me when building with Nix.

**Comment by jgm** [comment]
fixed in the 1.19.2.2 release.

note that the dev version's Setup.hs works with both Cabal < 2 and >= 2.
